apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: m3
        image: kamaleshsomasundaram/final_try:v25.0 #v20.0 is without testing functions
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_HOST
            value: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
